my:
  datasource:
    url: local.db.com
    username: username
    password: password
    etc:
      max-connection: 1
      timeout: 60s
      options: LOCAL,CACHE
---
spring:
  config:
    activate:
      on-profile: dev

my:
  datasource:
    url: dev.db.com
    username: dev
    password: dev
    etc:
      max-connection: 10
      timeout: 60s
      options: LOCAL,CACHE
---
spring:
  config:
    activate:
      on-profile: prod

my:
  datasource:
    url: prod.db.com
    username: prod
    password: prod
    etc:
      max-connection: 50
      timeout: 60s
      options: LOCAL,CACHE