management:
  server:
    port: 8080
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: "full"
#  endpoint:
#    shutdown:
#      enabled: true
  endpoint:
    health:
#      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"
#      base-path: "/manage"
#    jmx:
#      exposure:
#        include: "health,info"

info:
  app:
    name: hello-actuator
    company: yh

logging:
  level:
    hello.controller: debug